# Generated by Django 6.0 on 2026-01-09 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=3)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo em Estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Estoque Mínimo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria')),
            ],
            options={
                'verbose_name_plural': 'Itens em Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_solicitante', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/Documento')),
                ('contato', models.CharField(max_length=100, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('data_saida', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Retirada')),
                ('data_prevista', models.DateField(verbose_name='Previsão de Devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data da Devolução Real')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Condições do Item / Obs')),
                ('devolvido', models.BooleanField(default=False, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item', verbose_name='Item Emprestado')),
            ],
            options={
                'verbose_name': 'Empréstimo Avulso',
                'verbose_name_plural': 'Controle de Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Doação/Compra)'), ('SAIDA', 'Saída (Uso/Consumo)')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('origem_destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem / Destino')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
