# Generated by Django 6.0 on 2026-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='motivo_falta',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Diferença (Perda/Quebra)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. Devolvida'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_emprestada',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtd. Levada'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
    ]
