# Generated by Django 6.0 on 2026-01-12 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_emprestimo_motivo_falta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.unidademedida', verbose_name='Unidade'),
        ),
    ]
