# Generated by Django 6.0.2 on 2026-02-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_unidademedida_alter_item_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='interno',
            field=models.BooleanField(default=False, verbose_name='Uso Interno'),
        ),
    ]
