# Generated by Django 6.0.2 on 2026-03-02 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_nucleo_tipoatividade_nucleo'),
        ('estoque', '0004_emprestimo_interno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_saida', '-id'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Controle de Empréstimos'},
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='interno',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_saida_real',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída (Real)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='email_solicitante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='logistica',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes de Logística'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.nucleo', verbose_name='Núcleo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_casa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável da Casa (quem entregou)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='tipo',
            field=models.CharField(choices=[('EXTERNO', 'Externo'), ('INTERNO', 'Interno / Operação')], default='EXTERNO', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_saida',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Saída (Prevista)'),
        ),
    ]
