# Generated by Django 6.0 on 2026-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_emprestimo_options_remove_emprestimo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='grupo_lote',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código do Lote'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='grupo_lote',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código do Lote'),
        ),
    ]
