# Generated by Django 6.0 on 2026-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_emprestimo_grupo_lote_movimentacao_grupo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='cpf_solicitante',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
