# Generated by Django 6.0 on 2026-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='SIGEP', max_length=100, verbose_name='Nome do Sistema')),
                ('logo', models.ImageField(blank=True, help_text='Imagem que aparece na sidebar e nos PDFs. Recomendado: PNG com fundo transparente.', null=True, upload_to='config/', verbose_name='Logo do Sistema')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
