# Generated by Django 6.0 on 2026-06-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosite',
            name='logo',
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone exibido na aba do navegador. Recomendado: PNG quadrado 32x32 ou 64x64.', null=True, upload_to='config/', verbose_name='Favicon (Ícone do Navegador)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo_relatorio',
            field=models.ImageField(blank=True, help_text='Imagem para o cabeçalho dos PDFs. Recomendado: PNG de alta qualidade.', null=True, upload_to='config/', verbose_name='Logo para Relatórios (PDF)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo_site',
            field=models.ImageField(blank=True, help_text='Imagem para o painel web. Recomendado: PNG com fundo transparente.', null=True, upload_to='config/', verbose_name='Logo do Site (Sidebar)'),
        ),
    ]
