# Generated by Django 6.0 on 2026-01-06 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Atividade (Ex: Treino, Aula)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_atividade', to='atividades.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Atividade')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Dia')),
                ('foto_1', models.ImageField(upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 1 (Obrigatória)')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 2')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 3')),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 4')),
                ('video_1', models.FileField(upload_to='atividades/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])], verbose_name='Vídeo 1 (Obrigatório)')),
                ('video_2', models.FileField(blank=True, null=True, upload_to='atividades/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])], verbose_name='Vídeo 2')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Monitor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.projeto', verbose_name='Projeto')),
                ('tipo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.tipoatividade', verbose_name='Atividade Realizada')),
            ],
            options={
                'verbose_name': 'Diário de Atividade',
                'verbose_name_plural': 'Diários de Atividades',
            },
        ),
    ]
