# Generated by Django 6.0 on 2026-02-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        ('beneficiarios', '0003_alter_beneficiario_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatividade',
            name='turnos',
            field=models.ManyToManyField(blank=True, to='beneficiarios.turno', verbose_name='Turnos Disponíveis'),
        ),
    ]
