# Generated by Django 6.0 on 2026-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_tipoatividade_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cor',
            field=models.CharField(default='#FFFFFF', help_text='Cor em Hexadecimal (ex: #FF0000)', max_length=7, verbose_name='Cor de Identificação'),
        ),
    ]
