# Generated by Django 6.0.2 on 2026-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_projeto_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroatividade',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='registroatividade',
            name='video_2',
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='foto_1',
            field=models.ImageField(upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='foto_2',
            field=models.ImageField(default='placeholder.jpg', upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='foto_3',
            field=models.ImageField(default='placeholder.jpg', upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='foto_4',
            field=models.ImageField(default='placeholder.jpg', upload_to='atividades/fotos/%Y/%m/', verbose_name='Foto 4'),
            preserve_default=False,
        ),
    ]
