# Generated by Django 6.0 on 2026-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_nucleo_tipoatividade_nucleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Inicial do Projeto'),
        ),
    ]
