# Generated by Django 6.0 on 2026-01-12 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta (Ex: Banco Brasil, Caixa)')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social (Fornecedor)')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('nota_fiscal', models.CharField(max_length=50, verbose_name='Doc. Fiscal / Nº Nota')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Dt. Emissão')),
                ('rubrica', models.CharField(max_length=100, verbose_name='Rúbrica (Ex: Material Consumo, RH)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('mes_referencia', models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês Ref.')),
                ('ano_referencia', models.IntegerField(default=2026, verbose_name='Ano Ref.')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('comprovante', models.FileField(upload_to='financeiro/notas/%Y/', verbose_name='NOTA (Arquivo)')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.conta', verbose_name='Saiu de qual conta?')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.projeto', verbose_name='Projeto Relacionado')),
                ('responsavel', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa (Prestação de Contas)',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DOACAO', 'Doação'), ('BAZAR', 'Venda de Bazar'), ('EVENTO', 'Evento'), ('VERBA', 'Verba/Convênio'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Recebimento')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.conta', verbose_name='Conta de Entrada')),
                ('responsavel', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita (Entrada)',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
