# Generated by Django 6.0 on 2026-01-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Receita',
                'verbose_name_plural': 'Categorias de Receita',
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Rúbrica')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
            },
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriareceita', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.rubrica', verbose_name='Rúbrica (Ex: Material Consumo, RH)'),
        ),
    ]
