# Generated by Django 6.0 on 2026-02-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_projeto_cor'),
        ('financeiro', '0002_categoriareceita_rubrica_alter_receita_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (Ex: 1.1, 1.2)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item (Ex: Equipe de Basquete)')),
            ],
            options={
                'verbose_name': 'Item de Despesa',
                'verbose_name_plural': 'Itens de Despesa',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='rubrica',
            options={'verbose_name': 'Rúbrica (Legado)', 'verbose_name_plural': 'Rúbricas (Legado)'},
        ),
        migrations.AddField(
            model_name='conta',
            name='projeto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.projeto', verbose_name='Projeto Vinculado'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Conta (Ex: Banco Brasil, Projeto X)'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.conta', verbose_name='Saiu de qual conta?'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.rubrica', verbose_name='Rúbrica (Legado)'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.itemdespesa', verbose_name='Item de Despesa'),
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (Ex: 1, 2.1)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Natureza (Ex: RH, Material)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Natureza de Despesa',
                'verbose_name_plural': 'Naturezas de Despesa',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='natureza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.naturezadespesa', verbose_name='Natureza Pai'),
        ),
    ]
