# Generated by Django 6.0.2 on 2026-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_itemdespesa_alter_rubrica_options_conta_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_inutilizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Inutilização'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='inutilizado',
            field=models.BooleanField(default=False, verbose_name='Inutilizado?'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='motivo_inutilizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Inutilização'),
        ),
    ]
