# Generated by Django 6.0 on 2026-04-30 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_despesa_data_inutilizacao_despesa_inutilizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExclusaoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despesa_id', models.IntegerField(verbose_name='ID da Despesa Original')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social (Fornecedor)')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Exclusão')),
                ('justificativa', models.TextField(verbose_name='Justificativa da Exclusão')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Exclusão Financeira',
                'verbose_name_plural': 'Logs de Exclusão Financeira',
                'ordering': ['-data_exclusao'],
            },
        ),
    ]
