# Generated by Django 6.0 on 2026-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone para Contato')),
                ('tem_problema_saude', models.BooleanField(default=False, verbose_name='Possui Quadro de Saúde?')),
                ('descricao_saude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual o quadro de saúde?')),
                ('necessita_acessibilidade', models.BooleanField(default=False, verbose_name='Necessita de Acessibilidade?')),
                ('descricao_acessibilidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual acessibilidade?')),
                ('projeto', models.CharField(max_length=100, verbose_name='Projeto')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade / Qtd. Atividades')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno')),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável')),
                ('grau_parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau de Parentesco')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PENDENTE', 'Pendente'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
