# Generated by Django 6.0 on 2026-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('nis', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIS/PIS')),
                ('renda_familiar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qtd_membros_familia', models.IntegerField(default=1, verbose_name='Qtd. Pessoas na Casa')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
