# Generated by Django 6.0 on 2026-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nis',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='qtd_membros_familia',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='renda_familiar',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='atividade',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Atividade / Qtd. Atividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='contato',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Contato (Tel/Email)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau de Parentesco'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='necessita_acessibilidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Necessita de Acessibilidade? Qual?'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='projeto',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='quadro_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quadro de Saúde Existente?'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PENDENTE', 'Pendente'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], default='Não Informado', max_length=20, verbose_name='Turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
