# Generated by Django 6.0 on 2026-01-12 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficiarios.turno', verbose_name='Turno'),
        ),
    ]
