# Generated by Django 6.0 on 2026-01-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        ('beneficiarios', '0002_turno_alter_beneficiario_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.tipoatividade', verbose_name='Atividade / Qtd. Atividades'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.projeto', verbose_name='Projeto'),
        ),
    ]
