# Generated by Django 6.0 on 2026-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_remove_beneficiario_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='quadro_saude',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='descricao_acessibilidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual acessibilidade?'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='descricao_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual o quadro de saúde?'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='telefone',
            field=models.CharField(default='Não Informado', max_length=20, verbose_name='Telefone para Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tem_problema_saude',
            field=models.BooleanField(default=False, verbose_name='Possui Quadro de Saúde?'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='necessita_acessibilidade',
            field=models.BooleanField(default=False, verbose_name='Necessita de Acessibilidade?'),
        ),
    ]
