# Generated by Django 6.0 on 2026-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_alter_beneficiario_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiarios/fotos/%Y/%m/', verbose_name='Foto do Beneficiário'),
        ),
    ]
