# Generated by Django 6.0.2 on 2026-03-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_nucleo_tipoatividade_nucleo'),
        ('beneficiarios', '0004_beneficiario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='turno',
        ),
        migrations.CreateModel(
            name='VinculoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.tipoatividade', verbose_name='Atividade')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='beneficiarios.beneficiario')),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.nucleo', verbose_name='Núcleo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atividades.projeto', verbose_name='Projeto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficiarios.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
            },
        ),
    ]
