# Generated by Django 6.0 on 2026-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0005_remove_beneficiario_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='nome_busca',
            field=models.CharField(blank=True, editable=False, help_text='Gerado automaticamente sem acentos para ordenação correta.', max_length=200, verbose_name='Nome para Ordenação'),
        ),
    ]
