# Generated by Django 6.0 on 2026-06-29 03:09

import unicodedata
from django.db import migrations


def strip_accents(text):
    if not text:
        return ''
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if not unicodedata.combining(c)).lower()


def populate_nome_busca(apps, schema_editor):
    Beneficiario = apps.get_model('beneficiarios', 'Beneficiario')
    for b in Beneficiario.objects.all():
        b.nome_busca = strip_accents(b.nome_completo)
        b.save(update_fields=['nome_busca'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0006_beneficiario_nome_busca'),
    ]

    operations = [
        migrations.RunPython(populate_nome_busca, reverse_noop),
    ]
